package edu.stevens.decision.tweetconsumer.hibernate.entities;
// Generated Apr 7, 2011 2:05:00 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Follow generated by hbm2java
 */
public class Follow  implements java.io.Serializable {


     private FollowId id;
     private Date followDate;

    public Follow() {
    }

    public Follow(FollowId id, Date followDate) {
       this.id = id;
       this.followDate = followDate;
    }
   
    public FollowId getId() {
        return this.id;
    }
    
    public void setId(FollowId id) {
        this.id = id;
    }
    public Date getFollowDate() {
        return this.followDate;
    }
    
    public void setFollowDate(Date followDate) {
        this.followDate = followDate;
    }




}


