package edu.stevens.decision.tweetconsumer.hibernate.entities;
// Generated Apr 7, 2011 2:05:00 PM by Hibernate Tools 3.2.1.GA



/**
 * FollowId generated by hbm2java
 */
public class FollowId  implements java.io.Serializable {


     private long userFollower;
     private long userFollowee;

    public FollowId() {
    }

    public FollowId(long userFollower, long userFollowee) {
       this.userFollower = userFollower;
       this.userFollowee = userFollowee;
    }
   
    public long getUserFollower() {
        return this.userFollower;
    }
    
    public void setUserFollower(long userFollower) {
        this.userFollower = userFollower;
    }
    public long getUserFollowee() {
        return this.userFollowee;
    }
    
    public void setUserFollowee(long userFollowee) {
        this.userFollowee = userFollowee;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FollowId) ) return false;
		 FollowId castOther = ( FollowId ) other; 
         
		 return (this.getUserFollower()==castOther.getUserFollower())
 && (this.getUserFollowee()==castOther.getUserFollowee());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getUserFollower();
         result = 37 * result + (int) this.getUserFollowee();
         return result;
   }   


}


