package edu.stevens.decision.tweetconsumer.hibernate.entities;
// Generated Apr 7, 2011 2:05:00 PM by Hibernate Tools 3.2.1.GA



/**
 * TwlsaId generated by hbm2java
 */
public class TwlsaId  implements java.io.Serializable {


     private int datasetId;
     private long tweetId;
     private int twlsaFrame;

    public TwlsaId() {
    }

    public TwlsaId(int datasetId, long tweetId, int twlsaFrame) {
       this.datasetId = datasetId;
       this.tweetId = tweetId;
       this.twlsaFrame = twlsaFrame;
    }
   
    public int getDatasetId() {
        return this.datasetId;
    }
    
    public void setDatasetId(int datasetId) {
        this.datasetId = datasetId;
    }
    public long getTweetId() {
        return this.tweetId;
    }
    
    public void setTweetId(long tweetId) {
        this.tweetId = tweetId;
    }
    public int getTwlsaFrame() {
        return this.twlsaFrame;
    }
    
    public void setTwlsaFrame(int twlsaFrame) {
        this.twlsaFrame = twlsaFrame;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TwlsaId) ) return false;
		 TwlsaId castOther = ( TwlsaId ) other; 
         
		 return (this.getDatasetId()==castOther.getDatasetId())
 && (this.getTweetId()==castOther.getTweetId())
 && (this.getTwlsaFrame()==castOther.getTwlsaFrame());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getDatasetId();
         result = 37 * result + (int) this.getTweetId();
         result = 37 * result + this.getTwlsaFrame();
         return result;
   }   


}


