package edu.stevens.decision.tweetconsumer.hibernate.entities;
// Generated Apr 7, 2011 2:05:00 PM by Hibernate Tools 3.2.1.GA



/**
 * TwseId generated by hbm2java
 */
public class TwseId  implements java.io.Serializable {


     private long tweetId;
     private int datasetId;

    public TwseId() {
    }

    public TwseId(long tweetId, int datasetId) {
       this.tweetId = tweetId;
       this.datasetId = datasetId;
    }
   
    public long getTweetId() {
        return this.tweetId;
    }
    
    public void setTweetId(long tweetId) {
        this.tweetId = tweetId;
    }
    public int getDatasetId() {
        return this.datasetId;
    }
    
    public void setDatasetId(int datasetId) {
        this.datasetId = datasetId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TwseId) ) return false;
		 TwseId castOther = ( TwseId ) other; 
         
		 return (this.getTweetId()==castOther.getTweetId())
 && (this.getDatasetId()==castOther.getDatasetId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getTweetId();
         result = 37 * result + this.getDatasetId();
         return result;
   }   


}


