package edu.stevens.decision.tweetconsumer.hibernate.entities;
// Generated Apr 7, 2011 2:05:00 PM by Hibernate Tools 3.2.1.GA



/**
 * Twse generated by hbm2java
 */
public class Twse  implements java.io.Serializable {


     private TwseId id;

    public Twse() {
    }

    public Twse(TwseId id) {
       this.id = id;
    }
   
    public TwseId getId() {
        return this.id;
    }
    
    public void setId(TwseId id) {
        this.id = id;
    }




}


