package edu.stevens.decision.tweetconsumer.hibernate.entities;
// Generated Apr 7, 2011 2:05:00 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private long userId;
     private String userName;
     private String userLogin;
     private String userLocation;
     private String userDescription;
     private Date userCreated;
     private Date userRecordUpdated;
     private Date userNetworkUpdated;

    public User() {
    }

	
    public User(long userId, Date userRecordUpdated) {
        this.userId = userId;
        this.userRecordUpdated = userRecordUpdated;
    }
    public User(long userId, String userName, String userLogin, String userLocation, String userDescription, Date userCreated, Date userRecordUpdated, Date userNetworkUpdated) {
       this.userId = userId;
       this.userName = userName;
       this.userLogin = userLogin;
       this.userLocation = userLocation;
       this.userDescription = userDescription;
       this.userCreated = userCreated;
       this.userRecordUpdated = userRecordUpdated;
       this.userNetworkUpdated = userNetworkUpdated;
    }
   
    public long getUserId() {
        return this.userId;
    }
    
    public void setUserId(long userId) {
        this.userId = userId;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getUserLogin() {
        return this.userLogin;
    }
    
    public void setUserLogin(String userLogin) {
        this.userLogin = userLogin;
    }
    public String getUserLocation() {
        return this.userLocation;
    }
    
    public void setUserLocation(String userLocation) {
        this.userLocation = userLocation;
    }
    public String getUserDescription() {
        return this.userDescription;
    }
    
    public void setUserDescription(String userDescription) {
        this.userDescription = userDescription;
    }
    public Date getUserCreated() {
        return this.userCreated;
    }
    
    public void setUserCreated(Date userCreated) {
        this.userCreated = userCreated;
    }
    public Date getUserRecordUpdated() {
        return this.userRecordUpdated;
    }
    
    public void setUserRecordUpdated(Date userRecordUpdated) {
        this.userRecordUpdated = userRecordUpdated;
    }
    public Date getUserNetworkUpdated() {
        return this.userNetworkUpdated;
    }
    
    public void setUserNetworkUpdated(Date userNetworkUpdated) {
        this.userNetworkUpdated = userNetworkUpdated;
    }




}


